// generated from ng_file_enum.ts.go
export enum Accidental_value {
	// insertion point	
	Accidental_valueSharp = "sharp",
	Accidental_valueNatural = "natural",
	Accidental_valueFlat = "flat",
	Accidental_valueDouble_sharp = "double-sharp",
	Accidental_valueSharp_sharp = "sharp-sharp",
	Accidental_valueFlat_flat = "flat-flat",
	Accidental_valueNatural_sharp = "natural-sharp",
	Accidental_valueNatural_flat = "natural-flat",
	Accidental_valueQuarter_flat = "quarter-flat",
	Accidental_valueQuarter_sharp = "quarter-sharp",
	Accidental_valueThree_quarters_flat = "three-quarters-flat",
	Accidental_valueThree_quarters_sharp = "three-quarters-sharp",
	Accidental_valueSharp_down = "sharp-down",
	Accidental_valueSharp_up = "sharp-up",
	Accidental_valueNatural_down = "natural-down",
	Accidental_valueNatural_up = "natural-up",
	Accidental_valueFlat_down = "flat-down",
	Accidental_valueFlat_up = "flat-up",
	Accidental_valueDouble_sharp_down = "double-sharp-down",
	Accidental_valueDouble_sharp_up = "double-sharp-up",
	Accidental_valueFlat_flat_down = "flat-flat-down",
	Accidental_valueFlat_flat_up = "flat-flat-up",
	Accidental_valueArrow_down = "arrow-down",
	Accidental_valueArrow_up = "arrow-up",
	Accidental_valueTriple_sharp = "triple-sharp",
	Accidental_valueTriple_flat = "triple-flat",
	Accidental_valueSlash_quarter_sharp = "slash-quarter-sharp",
	Accidental_valueSlash_sharp = "slash-sharp",
	Accidental_valueSlash_flat = "slash-flat",
	Accidental_valueDouble_slash_flat = "double-slash-flat",
	Accidental_valueSharp_1 = "sharp-1",
	Accidental_valueSharp_2 = "sharp-2",
	Accidental_valueSharp_3 = "sharp-3",
	Accidental_valueSharp_5 = "sharp-5",
	Accidental_valueFlat_1 = "flat-1",
	Accidental_valueFlat_2 = "flat-2",
	Accidental_valueFlat_3 = "flat-3",
	Accidental_valueFlat_4 = "flat-4",
	Accidental_valueSori = "sori",
	Accidental_valueKoron = "koron",
	Accidental_valueOther = "other",
}

export interface Accidental_valueSelect {
	value: string;
	viewValue: string;
}

export const Accidental_valueList: Accidental_valueSelect[] = [ // insertion point	
	{ value: Accidental_value.Accidental_valueSharp, viewValue: "sharp" },
	{ value: Accidental_value.Accidental_valueNatural, viewValue: "natural" },
	{ value: Accidental_value.Accidental_valueFlat, viewValue: "flat" },
	{ value: Accidental_value.Accidental_valueDouble_sharp, viewValue: "double-sharp" },
	{ value: Accidental_value.Accidental_valueSharp_sharp, viewValue: "sharp-sharp" },
	{ value: Accidental_value.Accidental_valueFlat_flat, viewValue: "flat-flat" },
	{ value: Accidental_value.Accidental_valueNatural_sharp, viewValue: "natural-sharp" },
	{ value: Accidental_value.Accidental_valueNatural_flat, viewValue: "natural-flat" },
	{ value: Accidental_value.Accidental_valueQuarter_flat, viewValue: "quarter-flat" },
	{ value: Accidental_value.Accidental_valueQuarter_sharp, viewValue: "quarter-sharp" },
	{ value: Accidental_value.Accidental_valueThree_quarters_flat, viewValue: "three-quarters-flat" },
	{ value: Accidental_value.Accidental_valueThree_quarters_sharp, viewValue: "three-quarters-sharp" },
	{ value: Accidental_value.Accidental_valueSharp_down, viewValue: "sharp-down" },
	{ value: Accidental_value.Accidental_valueSharp_up, viewValue: "sharp-up" },
	{ value: Accidental_value.Accidental_valueNatural_down, viewValue: "natural-down" },
	{ value: Accidental_value.Accidental_valueNatural_up, viewValue: "natural-up" },
	{ value: Accidental_value.Accidental_valueFlat_down, viewValue: "flat-down" },
	{ value: Accidental_value.Accidental_valueFlat_up, viewValue: "flat-up" },
	{ value: Accidental_value.Accidental_valueDouble_sharp_down, viewValue: "double-sharp-down" },
	{ value: Accidental_value.Accidental_valueDouble_sharp_up, viewValue: "double-sharp-up" },
	{ value: Accidental_value.Accidental_valueFlat_flat_down, viewValue: "flat-flat-down" },
	{ value: Accidental_value.Accidental_valueFlat_flat_up, viewValue: "flat-flat-up" },
	{ value: Accidental_value.Accidental_valueArrow_down, viewValue: "arrow-down" },
	{ value: Accidental_value.Accidental_valueArrow_up, viewValue: "arrow-up" },
	{ value: Accidental_value.Accidental_valueTriple_sharp, viewValue: "triple-sharp" },
	{ value: Accidental_value.Accidental_valueTriple_flat, viewValue: "triple-flat" },
	{ value: Accidental_value.Accidental_valueSlash_quarter_sharp, viewValue: "slash-quarter-sharp" },
	{ value: Accidental_value.Accidental_valueSlash_sharp, viewValue: "slash-sharp" },
	{ value: Accidental_value.Accidental_valueSlash_flat, viewValue: "slash-flat" },
	{ value: Accidental_value.Accidental_valueDouble_slash_flat, viewValue: "double-slash-flat" },
	{ value: Accidental_value.Accidental_valueSharp_1, viewValue: "sharp-1" },
	{ value: Accidental_value.Accidental_valueSharp_2, viewValue: "sharp-2" },
	{ value: Accidental_value.Accidental_valueSharp_3, viewValue: "sharp-3" },
	{ value: Accidental_value.Accidental_valueSharp_5, viewValue: "sharp-5" },
	{ value: Accidental_value.Accidental_valueFlat_1, viewValue: "flat-1" },
	{ value: Accidental_value.Accidental_valueFlat_2, viewValue: "flat-2" },
	{ value: Accidental_value.Accidental_valueFlat_3, viewValue: "flat-3" },
	{ value: Accidental_value.Accidental_valueFlat_4, viewValue: "flat-4" },
	{ value: Accidental_value.Accidental_valueSori, viewValue: "sori" },
	{ value: Accidental_value.Accidental_valueKoron, viewValue: "koron" },
	{ value: Accidental_value.Accidental_valueOther, viewValue: "other" },
];
