// generated from ng_file_enum.ts.go
export enum Kind_value {
	// insertion point	
	Kind_valueMajor = "major",
	Kind_valueMinor = "minor",
	Kind_valueAugmented = "augmented",
	Kind_valueDiminished = "diminished",
	Kind_valueDominant = "dominant",
	Kind_valueMajor_seventh = "major-seventh",
	Kind_valueMinor_seventh = "minor-seventh",
	Kind_valueDiminished_seventh = "diminished-seventh",
	Kind_valueAugmented_seventh = "augmented-seventh",
	Kind_valueHalf_diminished = "half-diminished",
	Kind_valueMajor_minor = "major-minor",
	Kind_valueMajor_sixth = "major-sixth",
	Kind_valueMinor_sixth = "minor-sixth",
	Kind_valueDominant_ninth = "dominant-ninth",
	Kind_valueMajor_ninth = "major-ninth",
	Kind_valueMinor_ninth = "minor-ninth",
	Kind_valueDominant_11th = "dominant-11th",
	Kind_valueMajor_11th = "major-11th",
	Kind_valueMinor_11th = "minor-11th",
	Kind_valueDominant_13th = "dominant-13th",
	Kind_valueMajor_13th = "major-13th",
	Kind_valueMinor_13th = "minor-13th",
	Kind_valueSuspended_second = "suspended-second",
	Kind_valueSuspended_fourth = "suspended-fourth",
	Kind_valueNeapolitan = "Neapolitan",
	Kind_valueItalian = "Italian",
	Kind_valueFrench = "French",
	Kind_valueGerman = "German",
	Kind_valuePedal = "pedal",
	Kind_valuePower = "power",
	Kind_valueTristan = "Tristan",
	Kind_valueOther = "other",
	Kind_valueNone = "none",
}

export interface Kind_valueSelect {
	value: string;
	viewValue: string;
}

export const Kind_valueList: Kind_valueSelect[] = [ // insertion point	
	{ value: Kind_value.Kind_valueMajor, viewValue: "major" },
	{ value: Kind_value.Kind_valueMinor, viewValue: "minor" },
	{ value: Kind_value.Kind_valueAugmented, viewValue: "augmented" },
	{ value: Kind_value.Kind_valueDiminished, viewValue: "diminished" },
	{ value: Kind_value.Kind_valueDominant, viewValue: "dominant" },
	{ value: Kind_value.Kind_valueMajor_seventh, viewValue: "major-seventh" },
	{ value: Kind_value.Kind_valueMinor_seventh, viewValue: "minor-seventh" },
	{ value: Kind_value.Kind_valueDiminished_seventh, viewValue: "diminished-seventh" },
	{ value: Kind_value.Kind_valueAugmented_seventh, viewValue: "augmented-seventh" },
	{ value: Kind_value.Kind_valueHalf_diminished, viewValue: "half-diminished" },
	{ value: Kind_value.Kind_valueMajor_minor, viewValue: "major-minor" },
	{ value: Kind_value.Kind_valueMajor_sixth, viewValue: "major-sixth" },
	{ value: Kind_value.Kind_valueMinor_sixth, viewValue: "minor-sixth" },
	{ value: Kind_value.Kind_valueDominant_ninth, viewValue: "dominant-ninth" },
	{ value: Kind_value.Kind_valueMajor_ninth, viewValue: "major-ninth" },
	{ value: Kind_value.Kind_valueMinor_ninth, viewValue: "minor-ninth" },
	{ value: Kind_value.Kind_valueDominant_11th, viewValue: "dominant-11th" },
	{ value: Kind_value.Kind_valueMajor_11th, viewValue: "major-11th" },
	{ value: Kind_value.Kind_valueMinor_11th, viewValue: "minor-11th" },
	{ value: Kind_value.Kind_valueDominant_13th, viewValue: "dominant-13th" },
	{ value: Kind_value.Kind_valueMajor_13th, viewValue: "major-13th" },
	{ value: Kind_value.Kind_valueMinor_13th, viewValue: "minor-13th" },
	{ value: Kind_value.Kind_valueSuspended_second, viewValue: "suspended-second" },
	{ value: Kind_value.Kind_valueSuspended_fourth, viewValue: "suspended-fourth" },
	{ value: Kind_value.Kind_valueNeapolitan, viewValue: "Neapolitan" },
	{ value: Kind_value.Kind_valueItalian, viewValue: "Italian" },
	{ value: Kind_value.Kind_valueFrench, viewValue: "French" },
	{ value: Kind_value.Kind_valueGerman, viewValue: "German" },
	{ value: Kind_value.Kind_valuePedal, viewValue: "pedal" },
	{ value: Kind_value.Kind_valuePower, viewValue: "power" },
	{ value: Kind_value.Kind_valueTristan, viewValue: "Tristan" },
	{ value: Kind_value.Kind_valueOther, viewValue: "other" },
	{ value: Kind_value.Kind_valueNone, viewValue: "none" },
];
