// generated from ng_file_enum.ts.go
export enum Metal_value {
	// insertion point	
	Metal_valueAgogo = "agogo",
	Metal_valueAlmglocken = "almglocken",
	Metal_valueBell = "bell",
	Metal_valueBellplate = "bell plate",
	Metal_valueBelltree = "bell tree",
	Metal_valueBrakedrum = "brake drum",
	Metal_valueCencerro = "cencerro",
	Metal_valueChainrattle = "chain rattle",
	Metal_valueChinesecymbal = "Chinese cymbal",
	Metal_valueCowbell = "cowbell",
	Metal_valueCrashcymbals = "crash cymbals",
	Metal_valueCrotale = "crotale",
	Metal_valueCymbaltongs = "cymbal tongs",
	Metal_valueDomedgong = "domed gong",
	Metal_valueFingercymbals = "finger cymbals",
	Metal_valueFlexatone = "flexatone",
	Metal_valueGong = "gong",
	Metal_valueHi_hat = "hi-hat",
	Metal_valueHigh_hatcymbals = "high-hat cymbals",
	Metal_valueHandbell = "handbell",
	Metal_valueJawharp = "jaw harp",
	Metal_valueJinglebells = "jingle bells",
	Metal_valueMusicalsaw = "musical saw",
	Metal_valueShellbells = "shell bells",
	Metal_valueSistrum = "sistrum",
	Metal_valueSizzlecymbal = "sizzle cymbal",
	Metal_valueSleighbells = "sleigh bells",
	Metal_valueSuspendedcymbal = "suspended cymbal",
	Metal_valueTamtam = "tam tam",
	Metal_valueTamtamwithbeater = "tam tam with beater",
	Metal_valueTriangle = "triangle",
	Metal_valueVietnamesehat = "Vietnamese hat",
}

export interface Metal_valueSelect {
	value: string;
	viewValue: string;
}

export const Metal_valueList: Metal_valueSelect[] = [ // insertion point	
	{ value: Metal_value.Metal_valueAgogo, viewValue: "agogo" },
	{ value: Metal_value.Metal_valueAlmglocken, viewValue: "almglocken" },
	{ value: Metal_value.Metal_valueBell, viewValue: "bell" },
	{ value: Metal_value.Metal_valueBellplate, viewValue: "bell plate" },
	{ value: Metal_value.Metal_valueBelltree, viewValue: "bell tree" },
	{ value: Metal_value.Metal_valueBrakedrum, viewValue: "brake drum" },
	{ value: Metal_value.Metal_valueCencerro, viewValue: "cencerro" },
	{ value: Metal_value.Metal_valueChainrattle, viewValue: "chain rattle" },
	{ value: Metal_value.Metal_valueChinesecymbal, viewValue: "Chinese cymbal" },
	{ value: Metal_value.Metal_valueCowbell, viewValue: "cowbell" },
	{ value: Metal_value.Metal_valueCrashcymbals, viewValue: "crash cymbals" },
	{ value: Metal_value.Metal_valueCrotale, viewValue: "crotale" },
	{ value: Metal_value.Metal_valueCymbaltongs, viewValue: "cymbal tongs" },
	{ value: Metal_value.Metal_valueDomedgong, viewValue: "domed gong" },
	{ value: Metal_value.Metal_valueFingercymbals, viewValue: "finger cymbals" },
	{ value: Metal_value.Metal_valueFlexatone, viewValue: "flexatone" },
	{ value: Metal_value.Metal_valueGong, viewValue: "gong" },
	{ value: Metal_value.Metal_valueHi_hat, viewValue: "hi-hat" },
	{ value: Metal_value.Metal_valueHigh_hatcymbals, viewValue: "high-hat cymbals" },
	{ value: Metal_value.Metal_valueHandbell, viewValue: "handbell" },
	{ value: Metal_value.Metal_valueJawharp, viewValue: "jaw harp" },
	{ value: Metal_value.Metal_valueJinglebells, viewValue: "jingle bells" },
	{ value: Metal_value.Metal_valueMusicalsaw, viewValue: "musical saw" },
	{ value: Metal_value.Metal_valueShellbells, viewValue: "shell bells" },
	{ value: Metal_value.Metal_valueSistrum, viewValue: "sistrum" },
	{ value: Metal_value.Metal_valueSizzlecymbal, viewValue: "sizzle cymbal" },
	{ value: Metal_value.Metal_valueSleighbells, viewValue: "sleigh bells" },
	{ value: Metal_value.Metal_valueSuspendedcymbal, viewValue: "suspended cymbal" },
	{ value: Metal_value.Metal_valueTamtam, viewValue: "tam tam" },
	{ value: Metal_value.Metal_valueTamtamwithbeater, viewValue: "tam tam with beater" },
	{ value: Metal_value.Metal_valueTriangle, viewValue: "triangle" },
	{ value: Metal_value.Metal_valueVietnamesehat, viewValue: "Vietnamese hat" },
];
